NumPy is the fundamental package for scientific computing with Python. It contains among other things:
<ul>
<li>a powerful N-dimensional array object</li>
<li>sophisticated (broadcasting) functions</li>
<li>tools for integrating C/C++ and Fortran code</li>
<li>useful linear algebra, Fourier transform, and random number capabilities</li>
</ul>

In [1]:
import numpy as np

<p>It's main object is it's homogenous multidimensional array</p>
<ul>
<li>Indexed by a tuple of positive integers</li>
<li>Dimensions are called axes</li>
<li>Number of axes is called rank</li>
</ul>

<p>The lenght of the array is simply the number of elements along a particular dimension (or in simple terms the number of the elements in the inner square brackets)</p>
<p>Eg the length of the numpy array [1,2,1] is 3 as the number of elements in it are 3 (1,2,1)</p>
<p>Eg the dimension of the above eg is 1 and the number of dimension(axis) of the array</p>
<p>
[[ 1., 0., 0.],<br>
 [ 0., 1., 2.]]</p>
 <p>is 2 and the lenght of the array is 3</p>

<p>Some numpy functions where our test array is A :</p>
<ul>
<li>A.shape --It is a tuple and you can access it like (a,b)=A.shape where b is the lenght of the array<li>
<li>A.size  --number of elements in the array</li>
<li>A.dtype --addiitonal to the python types numpy also provides some like numpy.int32, numpy.int16, and numpy.float64</li>
<li>A.itemsize--the size in bytes the each element of the array</li>
</ul>

In [2]:
a = np.arange(15).reshape(3,5)
#Here the arange is used to get numbers from 0 to 15 and reshape is used to get the matrix of the desired size
print ("A.shape = ",a.shape)
print ("A.size =",a.size)
print ("A.dtype =",a.dtype)
print ("A.itemsize =",a.itemsize)
print ("type(a) =",type(a))

A.shape =  (3, 5)
A.size = 15
A.dtype = int64
A.itemsize = 8
type(a) = <class 'numpy.ndarray'>


In [3]:
# To create array use np.array()
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
c = np.array([[1],[2,3]])
print ("a = ",a)
print ("b = ",b)
print ("c = ",c)
#Note that although c can be created but it is cannot be considered an multidimensional array 
#as the number of elements along every row must be same 

a =  [1 2 3]
b =  [[1 2]
 [3 4]]
c =  [[1] [2, 3]]


In [4]:
#Now the working of arrange.
# Arrange will give you a array of continous numbers 'arange(a,b)' from [a,b)
print ("First = ",np.arange(1.,16.))
# Now arrange can also be used in the same way as range in Python.
# If you want a sequence of numbers
print ("Second = ",np.arange(10,30,6))
# Now you can also do 
print ("Third = ",np.arange(0, 2, 0.3))
# But it is not recommended as it is difficult to know in advance which numbers will be outputted
# Due to the floating point precision
# To overcome this problem use 'linspace' instead
#It will take two numbers as input that will specify the start and end of the range
#and a third number that will tell in how much parts do you want to divide the specified range.
print ("Fourth = ",np.linspace(0,2,9))

First =  [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.]
Second =  [10 16 22 28]
Third =  [ 0.   0.3  0.6  0.9  1.2  1.5  1.8]
Fourth =  [ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


In [5]:
# Now as an example if you want the values of the sine function you can do 
x = np.linspace(0,2*np.pi,100)
f = np.sin(x)
print (f)
#Now if you know matplotlib you can also plot it and you will get the complete sin wave

[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-01   1.58001396e-01
   9.50560433e-02   3.17279335e-02  -3.17279335e-02  -9.50560433e-02
  -1.58001396e-01  -2.20310533e-01  -2.81732557e-01  -3.42020143e-01
  -4.00930535e-01  -4.58226522e-01

In [6]:
#the type of arrat can be explicitly specified at the start
a = np.array([[1,2,3],[4,5,6]], dtype=float)
b = np.array([[1,2,3],[4,5,6]], dtype=complex)

In [7]:
print (a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [8]:
print (b)

[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j]]


<p>Now a thing to note is that exapanding array is an expensive operation. So after creating an array for optimization purposes it is not recommended that the size of the array be expanded<p>
<p>Now when we are given a problem we usually know the size of the array. So we can create placeholders that we will later use to store out data</p>
<p>Different placeholders:
<ul>
<li>np.zeros(size)</li>
<li>np.ones(size)</li>
<li>np.empty(size)</li>
<li>np.eye()</li>
</ul>
</p>

In [8]:
a = np.zeros((4,6))
b = np.ones((3,3), dtype=np.float64)
c = np.empty((3,3))
d = np.eye(4)
print (a,"\n")
print (b,"\n")
print (c,"\n")
print (d)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]] 

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] 

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [10]:
# Now if you are given a array and you want another placeholder array of the same dimension
# you can use zeros_like,ones_like
x = np.arange(20).reshape(4,5)
a = np.zeros_like(x)
b = np.ones_like(x)
c = np.empty_like(x, dtype=complex)
print ("a=\n",a,"\n")
print ("b=\n",b,"\n")
print ("c=\n",c)

a=
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

b=
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

c=
 [[  6.93744630e-310 +9.04797042e-317j   6.93744198e-310 +6.93744187e-310j
   -6.62990804e-129 +6.93744724e-310j   6.93744187e-310 -9.84997258e-147j
    6.93744720e-310 +6.93744187e-310j]
 [  8.36062477e-181 +6.93744201e-310j   6.93744187e-310 -2.88202164e+010j
    6.93744724e-310 +6.93744187e-310j   0.00000000e+000 +0.00000000e+000j
    0.00000000e+000 +0.00000000e+000j]
 [  0.00000000e+000 +0.00000000e+000j   0.00000000e+000 +0.00000000e+000j
    0.00000000e+000 +0.00000000e+000j   0.00000000e+000 +0.00000000e+000j
    1.13990216e-094 +4.79243676e-322j]
 [  9.66592401e-317 +6.93744630e-310j   9.08367217e+223 +7.34746839e+223j
    9.30214383e+242 +8.82893671e+199j   2.58276550e-144 +4.31714561e-320j
    0.00000000e+000 +0.00000000e+000j]]


<p>There are some random funcitons that can be used to create placeholders:
<ul>
<li>np.random.rand --</li>
<li>np.random.randn --</li>
<li>np.random.random --</li>
</ul>
<p>The difference betweeen rand and randn is that randn returns numbers from a standard normal distribuition that has mean = 0 and standard deviation = 1 while rand simply gives you numbers between the range [0,1)</p>
<p>In general whenever you want positive random numbers you use rand and when you want both positive and negative random numbers you use randn</p>
<p>np.random.random returns random floats in the half of open interval [0.0,1.0). Results are from the "continous uniform" distribuition over the stated interval. Now to sample the it multiply by (b-a)*random_smaple()+a</p>
</p>

In [11]:
a = np.random.rand(3,2)
b = np.random.randn(3,2)
print ("a=\n",a,"\n")
print ("b=\n",b)

a=
 [[ 0.1032316   0.77564211]
 [ 0.10924713  0.20711719]
 [ 0.22763973  0.2187961 ]] 

b=
 [[ 0.4499937   0.54005289]
 [ 1.66450879 -0.54349252]
 [-0.23731536 -0.93270856]]


In [12]:
#np.random.random
a = np.random.random((3,4))
print ("a=\n",a,"\n")
b = np.random.random_sample((3,4))
print ("b=\n",b,"\n")
#in simple terms when you want some array of random numbers  d
c = 6*np.random.random((3,4))-5
print ("c=\n",c)

a=
 [[ 0.75178924  0.59406927  0.30461803  0.24449067]
 [ 0.92223926  0.65031612  0.36075147  0.78902744]
 [ 0.9985204   0.56280867  0.81960449  0.02675115]] 

b=
 [[ 0.53134567  0.17956271  0.32254833  0.97086802]
 [ 0.12645491  0.04805484  0.80099095  0.04711127]
 [ 0.16398355  0.86880829  0.05363758  0.61557857]] 

c=
 [[-2.65316809 -4.63781085 -0.27271188 -2.60287858]
 [-3.62305498 -4.33186762 -1.89852868 -0.2340256 ]
 [-1.21368269 -0.34327308 -2.84562406  0.73788249]]


In [13]:
#when the size of the array is too large to be printed on the screen 
#then the central part is automatically skipped 
a = np.arange(10000).reshape(100,100)
print (a)
#to overcome this difficulty use 
#'np.set_printoptions(threshold='value')'
#Now you can set the value to nan if you want to dispaly all the numbers of the array

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [14]:
#now if you want to set the precision of all the numbers in an array generated by random numbers
np.set_printoptions(precision=4)
print (np.random.randn(3,4),"\n")
#if you want to display the complete array
np.set_printoptions(threshold=100000)
print (np.random.randn(50,50))

[[ 1.5874  0.1089  0.2465  0.6434]
 [ 1.1251  0.0298 -1.7749  0.0546]
 [ 0.7295 -0.8496  0.6311 -0.4474]] 

[[ -2.5111e-01  -3.5382e-01   1.0404e+00   2.2161e+00   4.5213e-01
   -1.5599e+00   1.0594e+00  -4.1610e-01   8.4213e-01  -6.0745e-01
   -9.1213e-01   5.0297e-01  -4.9355e-02  -5.8003e-01   6.8286e-01
   -1.2117e-01   2.5396e-01   2.3750e+00  -3.8656e-01   1.0581e+00
    5.6547e-01   5.9946e-01  -8.1017e-01   1.9594e+00   1.2092e-01
   -6.4453e-01   3.9103e-01  -5.0583e-01   1.5389e+00  -1.1411e+00
    5.7868e-01  -1.9169e+00   1.8749e+00   2.1851e-01  -3.8174e-01
   -1.7268e+00  -7.0776e-02   1.1640e+00   1.2525e+00  -4.6767e-01
   -6.0340e-02  -2.5667e-01  -2.0955e+00   1.0164e+00  -1.7491e-01
   -7.5127e-01  -1.3473e+00  -3.8305e-01  -1.8869e+00  -2.1650e-01]
 [  1.7448e+00  -4.1420e-01  -1.7430e-01  -1.0925e+00   3.7825e-01
    3.9956e-01   9.7354e-01  -7.2090e-01  -2.6430e-01   6.8714e-01
    6.7966e-01  -4.8687e-01   5.5124e-01   2.6462e-01  -1.0898e-01
    1.8052e+00  -1.0

<h1>Basic operations</h1>

In [15]:
a = np.array([10,20,30,40])
np.set_printoptions(precision=2)
b = 10*np.random.rand(3,4)
print (a,"\n")
print (b)

[10 20 30 40] 

[[ 7.11  9.21  7.12  8.74]
 [ 9.79  9.15  8.03  6.09]
 [ 0.14  2.22  7.15  8.99]]


<h3>Add</h3>

In [16]:
#you can add a element to all the array
print (a+3)

[13 23 33 43]


In [17]:
#you can add numbers to entire array
print (a + np.arange(4))

[10 21 32 43]


In [18]:
#you can add numbers to the rows of the matrix like example 1
print (b + np.arange(3).reshape(3,1))
#here it adds 0 to all the elements of the first row
#then 1 to all elements of the second row
#then 2 to all elements of the third row

[[  7.11   9.21   7.12   8.74]
 [ 10.79  10.15   9.03   7.09]
 [  2.14   4.22   9.15  10.99]]


In [19]:
#to add numbers to the columns of the matrix
print (b + np.arange(4).reshape(1,4))
# here it add 0 to the first column
# then 1 to all the elements of the second column and so on

[[  7.11  10.21   9.12  11.74]
 [  9.79  10.15  10.03   9.09]
 [  0.14   3.22   9.15  11.99]]


<h3>Subtraction</h3>

<p>All the opeartions of the addition can be applied to subtraction</p>

<h3>Multiply</h3>
<p>Now * operator does elementwise multiplication in numpy</p>

In [20]:
a = np.arange(4).reshape(2,2)
b = np.array([[3,4],[10,20]])
print (a*b)

[[ 0  4]
 [20 60]]


In [21]:
#To do matrix multipication or in other terms take dot product of the matrixes 
print (np.dot(a,b),"\n")
#or you can do
print (a.dot(b))
#but i personally prefer the first one

[[10 20]
 [36 68]] 

[[10 20]
 [36 68]]


In [22]:
#you can also use opeartions like += or *=

<h3>Sum of array</h3>

In [23]:
a = np.random.random((2,1))
print (a)
print (a.sum())
#now the reason that it is showing precision of 2 in the matrix is because i earlier changed
#the set_printoptions(precision=2)

[[ 0.69]
 [ 0.6 ]]
1.28697215998


<h3>Min and max of array</h3>

In [24]:
a = np.random.random((2,3))
print (a)
minimum = a.min()
maximum = a.max()
print ("Minimum element in the array is ",minimum)
print ("maximum element in the array is ",maximum)

[[ 0.65  0.28  0.3 ]
 [ 0.04  0.46  0.08]]
Minimum element in the array is  0.0388853476985
maximum element in the array is  0.64548072345


In [25]:
#now by default these opeartions work on the entire array as a list
#but you can do these operations along different axis
a = np.arange(12).reshape(3,4)
print (a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
a.sum()

66

In [27]:
a.min(axis = 0)
#it finds the minimum along all the columns

array([0, 1, 2, 3])

In [28]:
a.min(axis = 1)
#it finds the minimum along all the rows

array([0, 4, 8])

In [29]:
a.cumsum()
#it is the cummulative sum of all the elements.
#How this works
#The array is treated as a list therefore the numbers become
#0,1,2,3,4,5,...
#and their cumulative sum becomes
#0,1,3,6,10,...

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [30]:
#cumulative sum along different axis
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [31]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

<h3>Universal Functions</h3>
<p>These operations operate elementwise on the array. These functions are sin,cos,exp,sqrt</p>

In [32]:
a = np.array([0,1,2,3])
exp = np.exp(a)
sqrt = np.sqrt(a)
print ("Exp = ",exp)
print ("Square root = ",sqrt)
print (np.add(a,exp))

Exp =  [  1.     2.72   7.39  20.09]
Square root =  [ 0.    1.    1.41  1.73]
[  1.     3.72   9.39  23.09]


<h3>All</h3>
<p>It is used to check whether all the elemets of the array are true or false. Now here all non-zero numbers are considered as true and 0 is condisered as false.</p>
<p>If all elements are true then it return True and if ant element is false it returns Fasle</p>

In [33]:
a = np.arange(4)
print (a)
print (a.all())

[0 1 2 3]
False


In [34]:
a = np.array([1,2,3,4,True])
print (a.all())

True


In [35]:
a = np.array([np.nan,1,1,2])
print (a.all())

True


<h3>Any</h3>
<p>It is similar to all but it checks whether any element is true or not.</p>

In [36]:
a = np.arange(4)
a.any()

True

In [37]:
a = np.array([np.nan,False,False])
a.any()

True

In [38]:
a = np.array([False,0])
a.any()

False

In [39]:
a = np.arange(10).reshape(2,5)
print ("a=\n",a,"\n")
print ("The square operation on the array\n",a**2)
#Now as ** operation works by multiplying the matrix the required number of times you are 
#basically doing matrix multipication and in numpy matrix multipication results in elementwise multipication

a=
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

The square operation on the array
 [[ 0  1  4  9 16]
 [25 36 49 64 81]]


<h1>Indexing, Slicing and Iterating</h1>

In [40]:
# Now the arrays defined in numpy are operated as lists 
# Therefore you can access the elements of array in the same way as a python list
a = np.arange(10)
print (a,"\n")
print ("a[8]=",a[8])
print ("\na[2:5]=",a[2:5])

[0 1 2 3 4 5 6 7 8 9] 

a[8]= 8

a[2:5]= [2 3 4]


In [41]:
# you can also do slicing with certain jumps or breaks
print ("a[:6:2]=",a[:6:2])
# As it starets with the starting element then it has to go 
# till 6 where 6 is in open range and with a jump of 2

a[:6:2]= [0 2 4]


In [42]:
# Now for multidimensional arrays
# These arrays can have one index per axis as in numpy dimensionis referred to as axis.
# Now the maximum number of axis is same as the rank of the array
# So the index for multidimensional array is given as a tuple
a = np.arange(20).reshape(4,5)
print ("a=\n",a)
print ("\na[2,3]=",a[2,3])

a=
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

a[2,3]= 13


In [43]:
# Now the slicing in multidimensioal arrays is same as single dimensioal array
# As we are now considering tuples of the form (a,b) here the slicin can be done as
# [:a,:b] or [3:a,4:b,3]
print (a[0:5,1])

[ 1  6 11 16]


In [44]:
# If this is getting confusing remember this 
# a corresponds to rows and b corresponds to columns
# so 0:5 in the above example means 0 row to 5-1 row and 
# 1 means the 1 column
# Now another thing to note here is that the indexing starts from 0
# So when i say first column i mean second column as the first column is indexed as 0=

In [45]:
# when lesser number of indexes are provided the rest are assumend to be complete slices
# or : in python language
print (a[1])
# here it wanted two indexes but we gave only one so it assumed the
# missing slice to be complete slice

[5 6 7 8 9]


In [46]:
print (a[-1])
# If you are familiar with negative indexing then in numpy it is the exact same as in python
print (a[-2,-4])

[15 16 17 18 19]
11


<p>The expression within brackets in a[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as a[i,...].</p>
<p>The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 array (i.e., it has 5 axes), then
<uL>
<li>x[1,2,...] is equivalent to x[1,2,:,:,:]</li>
<li>x[...,3] to x[:,:,:,:,3]</li>
<li>x[4,...,5,:] to x[4,:,:,5,:]</li></ul></p>

In [47]:
# But as a programmer it is not a optimal way of doing things as 
# These lead to more runtime errors as it becomes harder to understanf your
# code

In [48]:
# Iterating over multidimensioal array is done with respect to the first axis
print ("a=\n",a,"\n")
for row in a:
    print (row)

a=
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [49]:
# If you want to iterate over all the elements of the array 
# you can use the attribute flat which is a iterator over all the 
# elements of the array
for element in a.flat:
    print (element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [50]:
# Another way to do above is to use nested for loops
(aSize,bSize)=a.shape
for row in range(aSize):
    for col in range(bSize):
        print (a[row,col])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


<h1>Shape Manipulation</h1>

In [5]:
temp = 10*np.random.random((3,4))
a = np.floor(temp)
print (temp,"\n")
print (a)
# what the floor attribute does it prints only the integral part of the float

[[ 1.24035708  6.08915058  0.08712495  1.47009232]
 [ 3.19199697  1.31281607  0.10783643  9.07673445]
 [ 0.31583778  1.09857611  0.76799868  6.55602409]] 

[[ 1.  6.  0.  1.]
 [ 3.  1.  0.  9.]
 [ 0.  1.  0.  6.]]


<p>The shape of an array can be changed in various ways. The three commands are
<ul>
<li>ravel</li>
The use of ravel is to flatten the array that is print the array as a list of numbers
<li>reshape</li>
The reshape is same as we have discussed earlier
<li>T</li>
It return the transpose of the array</ul></p>

In [24]:
a = np.arange(1,25).reshape((3,4,2))
print (a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [25]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [26]:
a.T

array([[[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]],

       [[ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22],
        [ 8, 16, 24]]])

In [30]:
a.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]])

In [31]:
a.reshape(24,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [22]:
# make sure that the product of the numbers you enter in reshape is
# equal to number of elements in the array
a.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [39]:
# The working of ravel
# Just remember that the rightmost index changes the fastest
# Initially you have a[0,0,0]
# Then a[0,0,1]
# Then a[0,0,2]

In [41]:
# There mat be some cases in which you don't know the size of array 
# or you only know only one dimension
# So you can put -1 instead of the original axis and the numpy will
# automatically compute the value to be use instead of -1 to make it a valid array
a = np.arange(32)
print (a.reshape(4,-1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [43]:
# Now if you want to join two arrays along different axis use
# stacking namely horizontal and vertical stacking
a = np.floor(10*np.random.random((2,3)))
b = np.floor(10*np.random.random((2,3)))
print (a,"\n")
print (b)

[[ 4.  2.  2.]
 [ 7.  7.  3.]] 

[[ 6.  0.  6.]
 [ 1.  7.  9.]]


In [46]:
np.vstack((a,b))

array([[ 4.,  2.,  2.],
       [ 7.,  7.,  3.],
       [ 6.,  0.,  6.],
       [ 1.,  7.,  9.]])

In [47]:
np.hstack((a,b))

array([[ 4.,  2.,  2.,  6.,  0.,  6.],
       [ 7.,  7.,  3.,  1.,  7.,  9.]])

In [52]:
a = np.floor(10*np.random.random((3,2,4)))
b = np.floor(10*np.random.random((3,2,4)))
print ("a=\n",a)
print ("\nb=\n",b)

a=
 [[[ 4.  5.  8.  9.]
  [ 3.  9.  4.  5.]]

 [[ 1.  7.  9.  1.]
  [ 7.  7.  1.  6.]]

 [[ 2.  5.  9.  1.]
  [ 5.  7.  8.  8.]]]

b=
 [[[ 7.  4.  1.  5.]
  [ 2.  5.  4.  3.]]

 [[ 3.  1.  7.  5.]
  [ 8.  1.  9.  4.]]

 [[ 9.  8.  2.  1.]
  [ 7.  0.  9.  3.]]]


In [54]:
np.hstack((a,b))

array([[[ 4.,  5.,  8.,  9.],
        [ 3.,  9.,  4.,  5.],
        [ 7.,  4.,  1.,  5.],
        [ 2.,  5.,  4.,  3.]],

       [[ 1.,  7.,  9.,  1.],
        [ 7.,  7.,  1.,  6.],
        [ 3.,  1.,  7.,  5.],
        [ 8.,  1.,  9.,  4.]],

       [[ 2.,  5.,  9.,  1.],
        [ 5.,  7.,  8.,  8.],
        [ 9.,  8.,  2.,  1.],
        [ 7.,  0.,  9.,  3.]]])

In [55]:
np.vstack((a,b))

array([[[ 4.,  5.,  8.,  9.],
        [ 3.,  9.,  4.,  5.]],

       [[ 1.,  7.,  9.,  1.],
        [ 7.,  7.,  1.,  6.]],

       [[ 2.,  5.,  9.,  1.],
        [ 5.,  7.,  8.,  8.]],

       [[ 7.,  4.,  1.,  5.],
        [ 2.,  5.,  4.,  3.]],

       [[ 3.,  1.,  7.,  5.],
        [ 8.,  1.,  9.,  4.]],

       [[ 9.,  8.,  2.,  1.],
        [ 7.,  0.,  9.,  3.]]])

In [57]:
# If you want to stack along any axis use concatenate
# It takes 2 arguments first a tuple of all the arrays
# and another the axis along which tou want to stack them
np.concatenate((a,b),axis=0)

array([[[ 4.,  5.,  8.,  9.],
        [ 3.,  9.,  4.,  5.]],

       [[ 1.,  7.,  9.,  1.],
        [ 7.,  7.,  1.,  6.]],

       [[ 2.,  5.,  9.,  1.],
        [ 5.,  7.,  8.,  8.]],

       [[ 7.,  4.,  1.,  5.],
        [ 2.,  5.,  4.,  3.]],

       [[ 3.,  1.,  7.,  5.],
        [ 8.,  1.,  9.,  4.]],

       [[ 9.,  8.,  2.,  1.],
        [ 7.,  0.,  9.,  3.]]])

In [58]:
# If you don't understand these stack functions forget about them
# As in real life we usually avoid such things
# But a basic knowledge about them can be helpful

<h3>Splitting of array</h3>

In [60]:
# if you want to split the array you can either use hspli or vspli
# But forgetting about them we can simply use array_split()
# which allows us to specify the axis along which to split
a = np.floor(10*np.random.random((2,12)))
print (a)

[[ 0.  4.  0.  1.  2.  3.  8.  3.  2.  8.  7.  2.]
 [ 3.  5.  6.  3.  1.  8.  1.  6.  7.  3.  5.  6.]]


In [62]:
np.array_split(a,1)

[array([[ 0.,  4.,  0.,  1.,  2.,  3.,  8.,  3.,  2.,  8.,  7.,  2.],
        [ 3.,  5.,  6.,  3.,  1.,  8.,  1.,  6.,  7.,  3.,  5.,  6.]])]

In [63]:
np.array_split(a,2)

[array([[ 0.,  4.,  0.,  1.,  2.,  3.,  8.,  3.,  2.,  8.,  7.,  2.]]),
 array([[ 3.,  5.,  6.,  3.,  1.,  8.,  1.,  6.,  7.,  3.,  5.,  6.]])]

In [5]:
#To copy contents of an array
a = np.random.random((3,2))
print (a)
b = a.copy()
print ("\n",b)

[[ 0.1318309   0.45606803]
 [ 0.74532002  0.02447613]
 [ 0.68278992  0.78698884]]

 [[ 0.1318309   0.45606803]
 [ 0.74532002  0.02447613]
 [ 0.68278992  0.78698884]]
